// <auto-generated />
using System;
using GebruikersbeheerZvz.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GebruikersbeheerZvz.Migrations
{
    [DbContext(typeof(GebruikersbeheerZvzContext))]
    [Migration("20230119210847_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorieen");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.CategorieRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CategorieenRollen");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tussenvoegsel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<int?>("GebruikerId")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Rollen");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Rol", b =>
                {
                    b.HasOne("GebruikersbeheerZvz.Models.Categorie", null)
                        .WithMany("Rollen")
                        .HasForeignKey("CategorieId");

                    b.HasOne("GebruikersbeheerZvz.Models.Gebruiker", null)
                        .WithMany("Rollen")
                        .HasForeignKey("GebruikerId");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Categorie", b =>
                {
                    b.Navigation("Rollen");
                });

            modelBuilder.Entity("GebruikersbeheerZvz.Models.Gebruiker", b =>
                {
                    b.Navigation("Rollen");
                });
#pragma warning restore 612, 618
        }
    }
}
